const http=require('http'), fs=require('fs'), path=require('path'); const {exercises}=require('./data/exercises'); const {stats,record}=require('./services/progress'); const {recommend}=require('./services/recommendation'); const python=require('./runners/pythonRunner');
const publicDir=path.join(__dirname,'public'); const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(data));};
function body(req){return new Promise((ok,no)=>{let d='';req.on('data',x=>d+=x);req.on('end',()=>{try{ok(JSON.parse(d||'{}'))}catch{no()}})})}
http.createServer(async(req,res)=>{ const url=new URL(req.url,'http://localhost');
 if(req.method==='GET'&&url.pathname==='/api/exercises') return json(res,200,exercises.map(({tests,solution,...e})=>e));
 if(req.method==='GET'&&url.pathname==='/api/dashboard'){const s=stats();return json(res,200,{stats:s,recommendation:recommend(s),daily:exercises[new Date().getDate()%exercises.length]});}
 if(req.method==='POST'&&url.pathname==='/api/run'){try{const b=await body(req),e=exercises.find(x=>x.id===b.exerciseId);if(!e)return json(res,404,{error:'Exercício não encontrado'}); const execution=await python.run(b.code,e.tests);return json(res,200,execution)}catch{return json(res,400,{error:'Dados inválidos'})}}
 if(req.method==='POST'&&url.pathname==='/api/submit'){try{const b=await body(req),e=exercises.find(x=>x.id===b.exerciseId);if(!e)return json(res,404,{error:'Exercício não encontrado'});const execution=await python.run(b.code,e.tests);if(execution.error)return json(res,200,execution);const passed=execution.results.every(x=>x.passed);const saved=record({exercise:e,passed,usedHints:b.usedHints});return json(res,200,{...execution,passed,...saved})}catch{return json(res,400,{error:'Dados inválidos'})}}
 let target=path.normalize(path.join(publicDir,url.pathname==='/'?'index.html':url.pathname)); if(!target.startsWith(publicDir)||!fs.existsSync(target)) return res.end('Não encontrado'); const type=target.endsWith('.css')?'text/css':target.endsWith('.js')?'application/javascript':'text/html';res.writeHead(200,{'Content-Type':type});fs.createReadStream(target).pipe(res);
}).listen(3000,()=>console.log('CodeGym em http://localhost:3000'));
